const APPROVE = 'APPROVE' as const;
const GET_CONTRACT_CREATION_PRICE = 'GET_CONTRACT_CREATION_PRICE' as const;
const CREATE_TOKEN_CONTRACT = 'CREATE_TOKEN_CONTRACT' as const;
const CREATE_LOSTKEY_CONTRACT = 'CREATE_LOSTKEY_CONTRACT' as const;
const CREATE_WILL_CONTRACT = 'CREATE_WILL_CONTRACT' as const;
const CREATE_CROWDSALE_CONTRACT = 'CREATE_CROWDSALE_CONTRACT' as const;
const CREATE_WEDDING_CONTRACT = 'CREATE_WEDDING_CONTRACT' as const;

// erc20
const GET_ERC20_SYMBOL = 'GET_ERC20_SYMBOL' as const;

const GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA = 'GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA' as const;

export default {
  GET_ERC20_SYMBOL,

  APPROVE,
  GET_CONTRACT_CREATION_PRICE,
  CREATE_TOKEN_CONTRACT,
  CREATE_LOSTKEY_CONTRACT,
  CREATE_WILL_CONTRACT,
  CREATE_CROWDSALE_CONTRACT,
  CREATE_WEDDING_CONTRACT,

  GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA,
};
