const APPROVE: 'APPROVE' = 'APPROVE';
const GET_CONTRACT_CREATION_PRICE: 'GET_CONTRACT_CREATION_PRICE' = 'GET_CONTRACT_CREATION_PRICE';
const CREATE_TOKEN_CONTRACT: 'CREATE_TOKEN_CONTRACT' = 'CREATE_TOKEN_CONTRACT';
const CREATE_LOSTKEY_CONTRACT: 'CREATE_LOSTKEY_CONTRACT' = 'CREATE_LOSTKEY_CONTRACT';
const CREATE_WILL_CONTRACT: 'CREATE_WILL_CONTRACT' = 'CREATE_WILL_CONTRACT';
const CREATE_CROWDSALE_CONTRACT: 'CREATE_CROWDSALE_CONTRACT' = 'CREATE_CROWDSALE_CONTRACT';
const CREATE_WEDDING_CONTRACT: 'CREATE_WEDDING_CONTRACT' = 'CREATE_WEDDING_CONTRACT';

// erc20
const GET_ERC20_SYMBOL: 'GET_ERC20_SYMBOL' = 'GET_ERC20_SYMBOL';

const GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA: 'GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA' = 'GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA';

export default {
  GET_ERC20_SYMBOL,

  APPROVE,
  GET_CONTRACT_CREATION_PRICE,
  CREATE_TOKEN_CONTRACT,
  CREATE_LOSTKEY_CONTRACT,
  CREATE_WILL_CONTRACT,
  CREATE_CROWDSALE_CONTRACT,
  CREATE_WEDDING_CONTRACT,

  GET_CROWDSALE_CONTRACT_ADDITIONAL_DATA,
};
