export const COLOR_AKZ = 'linear-gradient(90deg, #70FF00 0%, #D4FB50 100%);';
export const COLOR_AKZ_1 = 'linear-gradient(90deg, #74E90D 0%, #D4FB50 0%, #74E90D 100%);';
export const COLOR_ACID_GREEN = '#70FF00';
export const COLOR_GREEN = '#212F1A';
export const COLOR_PURPLE = '#8F00FF';
export const COLOR_PINK = '#FF2B91';
export const COLOR_ORANGE = '#FEA129';

export const COLOR_WHITE = '#ffffff';
export const COLOR_BLACK = '#000000';
export const COLOR_BLACK_1 = '#191A1D';
export const COLOR_BLACK_2 = '#1E2023';
export const COLOR_BLACK_3 = '#25272E';
export const COLOR_BLACK_4 = '#64656A';
export const COLOR_BLACK_5 = '#192038';
export const COLOR_BLACK_6 = '#131417';
export const COLOR_BLACK_7 = '#111215';
export const COLOR_BLACK_8 = '#151114';
export const COLOR_BLACK_9 = 'rgba(217, 217, 217, 0.1)';

export const COLOR_BLACK_SCALE_5 = 'rgba(0, 0, 0, .5)';

export const COLOR_GREY = '#F2F2F2';
export const COLOR_GREY_1 = '#C4C4C4';
export const COLOR_GREY_2 = '#B5BDCE';
export const COLOR_GREY_3 = '#DAE3F5';
export const COLOR_GREY_4 = '#C5CEE0';
export const COLOR_GREY_5 = '#6C778F';
export const COLOR_GREY_6 = '#2E3A59';
export const COLOR_GREY_7 = '#A7AEBD';
export const COLOR_GREY_8 = '#EDF3FF';
export const COLOR_GREY_9 = '#B5BDCE';

export const COLOR_YELLOW = '#F2C94C';

export const COLOR_ERROR = '#FF4040';

export const COLOR_BUTTON_PRIMARY_DARK_DEFAULT = COLOR_BLACK_6;
export const COLOR_BUTTON_PRIMARY_DARK_HOVER = COLOR_AKZ;
export const COLOR_BUTTON_PRIMARY_DARK_ACTIVE = COLOR_ACID_GREEN;
export const COLOR_BUTTON_PRIMARY_DARK_DISABLED = COLOR_BLACK_1;

export const COLOR_BUTTON_SECONDARY_DARK_DEFAULT = COLOR_AKZ;
export const COLOR_BUTTON_SECONDARY_DARK_HOVER = COLOR_AKZ_1;
export const COLOR_BUTTON_SECONDARY_DARK_ACTIVE = COLOR_ACID_GREEN;
export const COLOR_BUTTON_SECONDARY_DARK_DISABLED = COLOR_BLACK_1;

export const COLOR_BUTTON_PRIMARY_LIGHT_DEFAULT = COLOR_GREY_3;
export const COLOR_BUTTON_PRIMARY_LIGHT_HOVER = COLOR_AKZ;
export const COLOR_BUTTON_PRIMARY_LIGHT_ACTIVE = COLOR_ACID_GREEN;
export const COLOR_BUTTON_PRIMARY_LIGHT_DISABLED = COLOR_GREY_3;

export const COLOR_BUTTON_SECONDARY_LIGHT_DEFAULT = COLOR_AKZ;
export const COLOR_BUTTON_SECONDARY_LIGHT_HOVER = COLOR_AKZ_1;
export const COLOR_BUTTON_SECONDARY_LIGHT_ACTIVE = COLOR_ACID_GREEN;
export const COLOR_BUTTON_SECONDARY_LIGHT_DISABLED = COLOR_GREY_3;

export const COLOR_LAYOUT_BACKGROUND_DARK = COLOR_BLACK_7;
export const COLOR_LAYOUT_BACKGROUND_LIGHT = COLOR_GREY_7;
