export default {
  USER_AUTH_RESET_PASSWORD: 'USER_AUTH_RESET_PASSWORD',
  USER_AUTH_CONFIRM_RESET_PASSWORD: 'USER_AUTH_CONFIRM_RESET_PASSWORD',
  USER_AUTH_CHANGE_PASSWORD: 'USER_AUTH_CHANGE_PASSWORD',
  USER_AUTH_REGISTER_ACCOUNT: 'USER_AUTH_REGISTER_ACCOUNT',
  USER_AUTH_LOGIN: 'USER_AUTH_LOGIN',
  USER_AUTH_LOGOUT: 'USER_AUTH_LOGOUT',
  USER_AUTH_GET_REGISTRATION_ACCOUNT_DATA: 'USER_AUTH_GET_REGISTRATION_ACCOUNT_DATA',
  USER_AUTH_CHECK_AUTHENTICATION: 'USER_AUTH_CHECK_AUTHENTICATION',
};
