export default {
  SETUP_MODAL_APPROVE: 'SETUP_MODAL_APPROVE',
  SETUP_MODAL_UPDATE_ALLOWANCE: 'SETUP_MODAL_UPDATE_ALLOWANCE',
  GET_SETUP_MODAL_TOKEN_ADDRESSES: 'GET_SETUP_MODAL_TOKEN_ADDRESSES',
  SETUP_MODAL_ADD_TOKENS: 'SETUP_MODAL_ADD_TOKENS',
};
