export default {
  ADMIN_CHECK_IS_ADMIN: 'ADMIN_CHECK_IS_ADMIN',
  ADMIN_SET_PAYMENTS_RECEIVER: 'ADMIN_SET_PAYMENTS_RECEIVER',
  ADMIN_SET_PRICE: 'ADMIN_SET_PRICE',
  ADMIN_GET_PAYMENTS_RECEIVER: 'ADMIN_GET_PAYMENTS_RECEIVER',
  ADMIN_GET_IS_MAINNET_DISABLED: 'ADMIN_GET_IS_MAINNET_DISABLED',
  ADMIN_SET_IS_MAINNET_DISABLED: 'ADMIN_SET_IS_MAINNET_DISABLED',
};
