export default {
  ADMIN_CHECK_IS_ADMIN: 'ADMIN_CHECK_IS_ADMIN',
  ADMIN_SET_PAYMENTS_RECEIVER: 'ADMIN_SET_PAYMENTS_RECEIVER',
  ADMIN_SET_PRICE: 'ADMIN_SET_PRICE',
  ADMIN_GET_PAYMENTS_RECEIVER: 'ADMIN_GET_PAYMENTS_RECEIVER',
  ADMIN_GET_IS_MAINNET_DISABLED: 'ADMIN_GET_IS_MAINNET_DISABLED',
  ADMIN_SET_IS_MAINNET_DISABLED: 'ADMIN_SET_IS_MAINNET_DISABLED',
  ADMIN_GET_USERS: 'ADMIN_GET_USERS',
  ADMIN_SEND_EMAIL: 'ADMIN_SEND_EMAIL',
  ADMIN_SET_IS_FROZEN_USER: 'ADMIN_SET_IS_FROZEN_USER',
  ADMIN_GET_USER_CONTRACTS: 'ADMIN_GET_USER_CONTRACTS',
  ADMIN_UPDATE_PERMISSIONS: 'ADMIN_UPDATE_PERMISSIONS',
};
