/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type NewContract = ContractEventLog<{
  contractAddress: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface LastWillFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): LastWillFactory;
  clone(): LastWillFactory;
  methods: {
    NATIVE(): NonPayableTransactionObject<string>;

    deployLastWill(
      tokenToPay: string,
      _backupAddresses: string[],
      _shares: (number | string | BN)[],
      _confirmationPeriod: number | string | BN,
      distributionReward: number | string | BN
    ): NonPayableTransactionObject<void>;

    getToken(_token: string): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    price(arg0: string): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setPrice(
      _token: string,
      _price: number | string | BN
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    NewContract(cb?: Callback<NewContract>): EventEmitter;
    NewContract(
      options?: EventOptions,
      cb?: Callback<NewContract>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "NewContract", cb: Callback<NewContract>): void;
  once(
    event: "NewContract",
    options: EventOptions,
    cb: Callback<NewContract>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
